[package]
name = "cardinal"
version = "0.1.0"
authors = ["embr <hi@liclac.eu>"]
edition = "2018"

[dependencies]
error-chain = "0"
log = "0.4"
simplelog = "^0.5.0"
pcsc = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
docopt = "1"
